version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - '/app/node_modules'
    env_file:
      - .env
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: polyclinic
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: polyclinic_dev
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    external: true
